$(document).ready (function(){

    var female1 = prompt("Please enter a female's name (1 of 2)");
  $('#female1-1').text(female1);
  $('#female1-2').text(female1);
  $('#female1-3').text(female1);
  var female2 = prompt("Please enter a female's name (2 of 2)");
  $('#female2-1').text(female2);
  $('#female2-2').text(female2);
  var male1 = prompt("Please enter a male's name");
  $('#male1-1').text(male1);
  $('#male1-2').text(male1);
  var state1 = prompt("Please enter a state name");
  $('#state1').text(state1);
  var occupation1 = prompt("Please enter the name of an occupation");
  $('#occupation1').text(occupation1);
  var noun1 = prompt("Please enter a noun (1 of 5)");
  $('#noun1').text(noun1);
  var noun2 = prompt("Please enter a noun (2 of 5)");
  $('#noun2').text(noun2);
  var noun3 = prompt("Please enter a noun (3 of 5)");
  $('#noun3').text(noun3);
  var noun4 = prompt("Please enter a noun (4 of 5)");
  $('#noun4').text(noun4);
  var noun5 = prompt("Please enter a noun (5 of 5)");
  $('#noun5').text(noun5);
  var color1 = prompt("Please enter the name of a color");
  $('#color1-1').text(color1);
  $('#color1-2').text(color1);
  $('#color1-3').text(color1);
  $('#color1-4').text(color1);
  var feature1 = prompt("Please enter the name of a feature");
  $('#feature1-1').text(feature1);
  $('#feature1-2').text(feature1);
});